package com.team.project.order;

public enum OrderStatus {

	DEPOSIT_STAY,
	DELIVERY,
	BEING_DELIVERY,
	DELIVERY_COMPLITE,
	PURCHASE_CONFIRMED,
	REQUEST_RETURN,
	RETURN_DONE,
	REQUEST_EXCHANGE,
	EXCHANGE_DONE,
	CANCEL_ORDER;
}
